 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

module Cadmin
  RSpec.describe "/email_custom_templates", type: :request do
        include Engine.routes.url_helpers
  
    # EmailCustomTemplate. As you add validations to EmailCustomTemplate, be sure to
    # adjust the attributes here as well.
    let(:valid_attributes) {
      skip("Add a hash of attributes valid for your model")
    }

    let(:invalid_attributes) {
      skip("Add a hash of attributes invalid for your model")
    }

    describe "GET /index" do
      it "renders a successful response" do
        EmailCustomTemplate.create! valid_attributes
        get email_custom_templates_url
        expect(response).to be_successful
      end
    end

    describe "GET /show" do
      it "renders a successful response" do
        email_custom_template = EmailCustomTemplate.create! valid_attributes
        get email_custom_template_url(email_custom_template)
        expect(response).to be_successful
      end
    end

    describe "GET /new" do
      it "renders a successful response" do
        get new_email_custom_template_url
        expect(response).to be_successful
      end
    end

    describe "GET /edit" do
      it "render a successful response" do
        email_custom_template = EmailCustomTemplate.create! valid_attributes
        get edit_email_custom_template_url(email_custom_template)
        expect(response).to be_successful
      end
    end

    describe "POST /create" do
      context "with valid parameters" do
        it "creates a new EmailCustomTemplate" do
          expect {
            post email_custom_templates_url, params: { email_custom_template: valid_attributes }
          }.to change(EmailCustomTemplate, :count).by(1)
        end

        it "redirects to the created email_custom_template" do
          post email_custom_templates_url, params: { email_custom_template: valid_attributes }
          expect(response).to redirect_to(email_custom_template_url(EmailCustomTemplate.last))
        end
      end

      context "with invalid parameters" do
        it "does not create a new EmailCustomTemplate" do
          expect {
            post email_custom_templates_url, params: { email_custom_template: invalid_attributes }
          }.to change(EmailCustomTemplate, :count).by(0)
        end

        it "renders a successful response (i.e. to display the 'new' template)" do
          post email_custom_templates_url, params: { email_custom_template: invalid_attributes }
          expect(response).to be_successful
        end
      end
    end

    describe "PATCH /update" do
      context "with valid parameters" do
        let(:new_attributes) {
          skip("Add a hash of attributes valid for your model")
        }

        it "updates the requested email_custom_template" do
          email_custom_template = EmailCustomTemplate.create! valid_attributes
          patch email_custom_template_url(email_custom_template), params: { email_custom_template: new_attributes }
          email_custom_template.reload
          skip("Add assertions for updated state")
        end

        it "redirects to the email_custom_template" do
          email_custom_template = EmailCustomTemplate.create! valid_attributes
          patch email_custom_template_url(email_custom_template), params: { email_custom_template: new_attributes }
          email_custom_template.reload
          expect(response).to redirect_to(email_custom_template_url(email_custom_template))
        end
      end

      context "with invalid parameters" do
        it "renders a successful response (i.e. to display the 'edit' template)" do
          email_custom_template = EmailCustomTemplate.create! valid_attributes
          patch email_custom_template_url(email_custom_template), params: { email_custom_template: invalid_attributes }
          expect(response).to be_successful
        end
      end
    end

    describe "DELETE /destroy" do
      it "destroys the requested email_custom_template" do
        email_custom_template = EmailCustomTemplate.create! valid_attributes
        expect {
          delete email_custom_template_url(email_custom_template)
        }.to change(EmailCustomTemplate, :count).by(-1)
      end

      it "redirects to the email_custom_templates list" do
        email_custom_template = EmailCustomTemplate.create! valid_attributes
        delete email_custom_template_url(email_custom_template)
        expect(response).to redirect_to(email_custom_templates_url)
      end
    end
  end
end
